#set language
language: java
jdk: oraclejdk8
#use user-mode
sudo: false

before_install:
- chmod +x mvnw

#after build start script, which will collect Jacoco statistics
after_success:
- bash <(curl -s https://codecov.io/bash)

#improve build speed
cache:
  directories:
  - $HOME/.m2